--liquibase formatted sql

--changeset vadim:1
--comment: Create core users table with basic profile information
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64) NOT NULL UNIQUE
);
--rollback:"DROP TABLE users"

--changeset vadim:2
--comment: Add table and column comments for users
COMMENT ON TABLE users IS 'Stores user profile information and subscriptions';
COMMENT ON COLUMN users.id IS 'Primary key, auto-incremented';
COMMENT ON COLUMN users.email IS 'Unique email address for authentication';

--changeset vadim:3
--comment: Create subscriptions information table
CREATE TABLE IF NOT EXISTS subscriptions
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(128) NOT NULL,
    start_date   DATE,
    user_id      BIGINT       NOT NULL REFERENCES users (id)
);
--rollback:"DROP TABLE subscriptions"

--changeset vadim:4
--comment: Add table and column comments for subscriptions
COMMENT ON TABLE subscriptions IS 'Contains subscriptions information';
COMMENT ON COLUMN subscriptions.id IS 'Primary key, auto-incremented';
COMMENT ON COLUMN subscriptions.service_name IS 'Name of the subscription service';
COMMENT ON COLUMN subscriptions.user_id IS 'Foreign key to users table';